[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flake8_drf_permissions"
version='0.1.0'


[project.entry-points."flake8.extension"]
PDR = "flake8_drf_permissions:Plugin"